name: Pull Request
on:
  pull_request_target:
    paths:
      - '01-teams/**'
      - '02-repositories/**'
      - '03-members/**'
  pull_request:
    paths-ignore:
      - '.github/workflows/provider-*.yaml'

jobs:
  preview-changes:
    name: Preview changes
    runs-on: ubuntu-latest
    steps:
      # Checkout code when the event is `pull_request`
      - name: Checkout code
        if: github.event_name == 'pull_request'
        uses: actions/checkout@v4
      # Checkout code when the event is `pull_request_target`
      - name: Checkout code
        if: github.event_name == 'pull_request_target'
        uses: actions/checkout@v4
        with:
          ref: '${{ github.event.pull_request.merge_commit_sha }}'

      - uses: volta-cli/action@v4

      - run: npm ci

      - uses: pulumi/actions@v5.2.4
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.ADMIN_GITHUB_TOKEN }}
        with:
          command: preview
          refresh: true
          stack-name: pulumiverse/prod
