name: Pull Request
on:
  pull_request:
    paths-ignore:
      - '.github/workflows/provider-*.yaml'

jobs:
  preview-changes:
    name: Preview changes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: volta-cli/action@v4
      - run: npm ci
      - uses: pulumi/actions@v5.2.4
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.ADMIN_GITHUB_TOKEN }}
        with:
          command: preview
          refresh: true
          stack-name: pulumiverse/prod
